spring.application.name=symptom-analyzer
# Database Connection

# Leave password blank if Postgres.app didn't ask you to set one. Otherwise, enter it here.

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Server Port
server.port=8080

# Gemini API Configuration
gemini.api.key=AIzaSyB1Mv9XS63IF32CzyGnCFHc3n1Yfy6OtT4
# Spring Boot Email Configuration (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# Email Config
spring.mail.username=${GMAIL_USER}
spring.mail.password=${GMAIL_APP_PASSWORD}

# Gemini Config
google.api.key=${GEMINI_API_KEY}

# Database Config (If using Neon)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
