spring.application.name=symptom-analyzer
# Database Connection

# Leave password blank if Postgres.app didn't ask you to set one. Otherwise, enter it here.

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Server Port
server.port=8080

# Gemini API Configuration
# Spring Boot Email Configuration (Gmail SMTP)
mailjet.api.key=${MAILJET_API_KEY}
mailjet.api.secret=${MAILJET_API_SECRET}

# Gemini Config
gemini.api.key=${GEMINI_API_KEY}

# Database Config (If using Neon)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
